### ISSUE TITLE
Worth changing the default branch to be gh-pages ?

### ISSUE THREAD

**Issue by davidboden** [stewdio/Cuber-DEMO#1]
I've forked and changed the branch name to be gh-pages.

All this does is allow Github to serve the project using it's github.io "pages" feature. Here's what it looks like:
http://daveboden.github.io/Cuber-DEMO

Might be worth moving it over from master to gh-pages here on the _real_ repository? (then I'll delete my fork...)

**Comment by davidboden** [comment]
Or, alternatively, start an _organisation_ called "cuber" and move the code to there? Organisation pages are served out of the master branch as detailed here: https://help.github.com/articles/user-organization-and-project-pages/

**Comment by stewdio** [comment]
Hi Dave. Thanks for the interest! I’m indeed aware of how a `gh-pages` branch works but I’m quite happy with only having the finished product as an easily visitable URL: http://iamthecu.be

I’ve only posted this repo as a view into how the project began (and how insane some of my code comments were—including ASCII art). Where this project ended up is far more interesting:
1. [Project description and background](http://stewd.io/w/rubikscube)
2. [Cube Explorer](http://iamthecu.be)
3. [Google’s Chrome Cube Lab](https://chrome.com/cubelab)
4. [Rubik’s Cube Google Doodle](https://www.google.com/doodles/rubiks-cube)

**Comment by davidboden** [comment]
Sounds reasonable, thanks. (didn't really think for a minute you weren't aware of gh-pages ;) )
